# Generated by Django 5.0.6 on 2024-06-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('symbol', models.CharField(max_length=3, unique=True)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'currency',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
                (
                    'data_type',
                    models.TextField(
                        choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'),
                                 ('boolean', 'Boolean'), ('json', 'Json')],
                        default='string'
                    )
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
