# Generated by Django 5.0.6 on 2024-06-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_setting_options_alter_setting_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='currency',
            table='currencies',
        ),
    ]
